### ISSUE TITLE
ESP32刷入固件后，无限重启

### ISSUE THREAD

**Issue by FlashSoft** [aliyun/TinyEngine#6]
2018-9-25 20:38:02:347 Rebooting...
2018-9-25 20:38:02:371 ets Jun  8 2016 00:22:57
2018-9-25 20:38:02:371 
2018-9-25 20:38:02:372 rst:0xc (SW_CPU_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
2018-9-25 20:38:02:372 configsip: 0, SPIWP:0xee
2018-9-25 20:38:02:372 clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
2018-9-25 20:38:02:372 mode:DIO, clock div:2
2018-9-25 20:38:02:372 load:0x3fff0010,len:4
2018-9-25 20:38:02:372 load:0xcf3f00c5,len:1754
2018-9-25 20:38:02:372 load:0x0a48529b,len:1208637705
2018-9-25 20:38:03:274 ets Jun  8 2016 00:22:57
2018-9-25 20:38:03:275 
2018-9-25 20:38:03:275 rst:0x10 (RTCWDT_RTC_RESET),boot:0x13 (SPI_FAST_FLASH_BOOT)
2018-9-25 20:38:03:275 configsip: 0, SPIWP:0xee
2018-9-25 20:38:03:275 clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
2018-9-25 20:38:03:275 mode:DIO, clock div:2
2018-9-25 20:38:03:275 load:0x3fff0010,len:4
2018-9-25 20:38:03:275 load:0x3fff0014,len:6248
2018-9-25 20:38:03:275 load:0x40078000,len:9308
2018-9-25 20:38:03:275 load:0x40080400,len:5780
2018-9-25 20:38:03:275 entry 0x40080744
2018-9-25 20:38:03:366 I (175) boot: ESP-IDF v3.2-dev-609-g51a4b4ba 2nd stage bootloader
2018-9-25 20:38:03:367 I (176) boot: compile time 21:34:05
2018-9-25 20:38:03:367 I (177) boot: Enabling RNG early entropy source...
2018-9-25 20:38:03:367 I (197) boot: SPI Speed      : 40MHz
2018-9-25 20:38:03:367 I (210) boot: SPI Mode       : DIO
2018-9-25 20:38:03:367 I (222) boot: SPI Flash Size : 4MB
2018-9-25 20:38:03:367 I (236) boot: Partition Table:
2018-9-25 20:38:03:367 I (246) boot: ## Label            Usage          Type ST Offset   Length
2018-9-25 20:38:03:367 I (269) boot:  0 nvs              WiFi data        01 02 00009000 00004000
2018-9-25 20:38:03:368 I (292) boot:  1 otadata          OTA data         01 00 0000d000 00002000
2018-9-25 20:38:03:368 I (315) boot:  2 phy_init         RF data          01 01 0000f000 00001000
2018-9-25 20:38:03:368 I (339) boot:  3 factory          factory app      00 00 00010000 00100000
2018-9-25 20:38:03:368 I (362) boot:  4 ota_0            OTA app          00 10 00110000 00100000
2018-9-25 20:38:03:368 I (385) boot:  5 ota_1            OTA app          00 11 00210000 00100000
2018-9-25 20:38:03:417 I (408) boot:  6 parameter1       unknown          40 00 00310000 00001000
2018-9-25 20:38:03:417 I (432) boot:  7 parameter2       unknown          40 00 00311000 00002000
2018-9-25 20:38:03:417 I (455) boot:  8 parameter3       unknown          40 00 00313000 00001000
2018-9-25 20:38:03:418 I (478) boot:  9 parameter4       unknown          40 00 00314000 00001000
2018-9-25 20:38:03:418 I (501) boot: 10 jsapp            Unknown data     01 82 00315000 00080000
2018-9-25 20:38:03:418 I (525) boot: End of partition table
2018-9-25 20:38:03:418 I (538) boot: Defaulting to factory image
2018-9-25 20:38:03:418 I (552) esp_image: segment 0: paddr=0x00010020 vaddr=0x3f400020 size=0x1f140 (127296) map
2018-9-25 20:38:03:514 I (855) esp_image: segment 1: paddr=0x0002f168 vaddr=0x3ffb0000 size=0x00ea8 (  3752) load
2018-9-25 20:38:03:514 I (866) esp_image: segment 2: paddr=0x00030018 vaddr=0x400d0018 size=0x96fe0 (618464) map
2018-9-25 20:38:03:963 I (2208) esp_image: segment 3: paddr=0x000c7000 vaddr=0x3ffb0ea8 size=0x01620 (  5664) load
2018-9-25 20:38:03:963 I (2223) esp_image: segment 4: paddr=0x000c8628 vaddr=0x40080000 size=0x00400 (  1024) load
2018-9-25 20:38:03:963 I (2232) esp_image: segment 5: paddr=0x000c8a30 vaddr=0x40080400 size=0x150d8 ( 86232) load
2018-9-25 20:38:04:033 I (2478) esp_image: segment 6: paddr=0x000ddb10 vaddr=0x400c0000 size=0x00000 (     0) load
2018-9-25 20:38:04:073 I (2554) boot: Loaded app from partition at offset 0x10000
2018-9-25 20:38:04:073 I (2554) boot: Disabling RNG early entropy source...
2018-9-25 20:38:04:073 I (1278) cpu_start: Pro cpu up.
2018-9-25 20:38:04:073 I (1283) cpu_start: Single core mode
2018-9-25 20:38:04:073 I (1292) cpu_start: Pro cpu start user code
2018-9-25 20:38:04:113 I (1321) cpu_start: Starting scheduler on PRO CPU.
2018-9-25 20:38:04:114 wifi_init:346 0
2018-9-25 20:38:04:114 E (1345) wifi: nvs_flash_init failed
2018-9-25 20:38:04:114 W (1345) wifi: wifi nvs_open fail ret=4353
2018-9-25 20:38:04:114 
2018-9-25 20:38:04:114 E (1345) wifi: wifi_init 1400 ret=4353
2018-9-25 20:38:04:114 ESP_ERROR_CHECK failed: esp_err_t 0x1101 at 0x4008ad25
2018-9-25 20:38:04:114 
2018-9-25 20:38:04:115 Backtrace: 0x40088fd0:0x3ffed820 0x4008931d:0x3ffed840 0x4008ad25:0x3ffed860 0x40107839:0x3ffed8c0 0x400899d6:0x3ffed8e0 0x40088012:0x3ffed900 0x40085555:0x3ffed920
2018-9-25 20:38:04:115 
2018-9-25 20:38:04:115 Rebooting...
2018-9-25 20:38:04:139 ets Jun  8 2016 00:22:57

**Comment by wuzhun1001** [comment]
你好，这是因为官方的ESP32的wifi参数与TinyEngine的固件有区别，所以第一次需要先全部erase flash一次。
请参考文档：ESP32固件烧录指南.md
![10_34_43__09_28_2018](https://user-images.githubusercontent.com/36021810/46184903-446ec700-c30a-11e8-9a02-4caa5fc7942e.jpg)

**Comment by FlashSoft** [comment]
好的
